version: '3.0'
services:
  web:
    image: realhimanshu/magento2:v1
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
  db:
    image: realhimanshu/magento2:v3
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
  phpmyadmin:
    image: realhimanshu/magento2:v2
    ports:
      - "8580:80"
    links:
      - db     
volumes:
  db-data: 